routes/web.php
<?php

use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\RatingsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::match(['get', 'post'], '/', [NewsController::class, 'index'])->name('home');
Route::resource('news', NewsController::class)->only('index','create', 'store','show');
Route::post('ratings', [RatingsController::class, 'store'])->name('store-rating')->middleware( 'auth');
Route::post('comments', [CommentsController::class, 'store'])->name('comments-store')->middleware( 'auth');
Route::get('users/{user}', [UsersController::class, 'show'])->name('show-user');


Route::prefix('admin')->middleware( 'auth')->name('admin.')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('admin-profile');
    Route::resource('news' ,App\Http\Controllers\Admin\NewsController::class)->except('show');
    Route::resource('comments' ,App\Http\Controllers\Admin\CommentController::class)->except('create','store','show');
    Route::post('comments-approve/{comment}', [CommentController::class, 'approve'])->name('comments-approve');
});

Auth::routes();

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = ['comments', 'approve', 'news_id', 'user_id'];

    /**
     * @return BelongsTo
     */
    public function news(): BelongsTo
    {
        return $this->belongsTo(News::class);
    }
    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CommentRequest;
use App\Models\Comment;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class CommentController extends Controller
{

    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws AuthorizationException
     */
    public function index()
    {
        $this->authorize('index', Comment::class);
        $comments = Comment::latest()->paginate(10);
        return view('admin.comments.index', compact('comments'));
    }


    /**
     * @param Comment $comment
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws AuthorizationException
     */
    public function edit(Comment $comment)
    {
        $this->authorize('edit', Comment::class);

        return view('admin.comments.edit', compact('comment'));
    }


    /**
     * @param CommentRequest $request
     * @param Comment $comment
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(CommentRequest $request, Comment $comment)
    {
        $this->authorize('update', Comment::class);
        $data = $request->all();
        $comment->update($data);

        return redirect()->route('admin.comments.index')
            ->with('status', "Comment update successfully!!!");
    }


    /**
     * @param Comment $comment
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Comment $comment)
    {
        $this->authorize('destroy', Comment::class);
        $comment->delete();
        return redirect()->action([self::class, 'index'])->with('status', "Comment successfully deleted!");
    }


    /**
     * @param Comment $comment
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function approve(Comment $comment)
    {
        $this->authorize('approve', Comment::class);
        $comment->approve = true;
        $comment->update();
        return redirect()->action([self::class, 'index'])->with('status', "Comment successfully approve!");
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CommentRequest;
use App\Models\Comment;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;

class CommentsController extends Controller
{

    /**
     * @param CommentRequest $request
     * @return RedirectResponse
     */
    public function store(CommentRequest $request)
    {
        if(Auth::check()) {
            $comment = new Comment();
            $comment->comment = $request->input('comments');
            $comment->news_id = $request->input('news_id');
            $comment->user_id = auth()->user()->id;

            $comment->save();

            return redirect()->back()->with('status', "Your comments is being reviewed");
        }
        return redirect()->route('login');
    }

}

resources/views/admin/comments/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mt-5">
        <div style="width: 80%; margin: 0 auto">
            <h2 class="mt-5">Update comment</h2>
            <form method="post" action="{{ route('admin.comments.update', ['comments' => $comment]) }}" enctype="multipart/form-data">
                @method('put')
                @csrf
                <div class="mb-3 mt-5" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <textarea type="text" name="text" class="form-control" placeholder="News text" aria-label="news_text"
                              aria-describedby="addon-wrapping">{{ $comment->comment }}</textarea>
                </div>
                @error('comments')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div style="width: 15%;margin: 0 auto;">
                    <button type="submit" style="padding: 8px 50px; color: black" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/comments/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mt-5">
        <div class="mt-3">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Comment</th>
                    <th scope="col">Approve</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($comments as $comment)
                    <tr>
                        <th scope="row">{{ $comment->id }}</th>
                        <td>{{ $comment->comment }}</td>
                        @if($comment->approve)
                            <td>approve</td>
                        @else
                            <td>
                                <form style="float: left; margin-right: 12px;"
                                      action="{{ route('admin.comments-approve', ['comment' => $comment]) }}"
                                      method="post">
                                    @csrf
                                    <button type="submit" class="btn btn-warning btn-sm active">Approve</button>
                                </form>
                            </td>

                        @endif
                        <td>
                            <div class="row">
                                <div class="col-6 box-btn">
                                    <a class="btn btn-outline-warning"
                                       href="{{ route('admin.comments.edit', ['comment' => $comment]) }}">Edit</a>
                                    <form style="float: left; margin-right: 12px;"
                                          action="{{ route('admin.comments.destroy', ['comment' => $comment]) }}"
                                          method="post">
                                        @method('delete')
                                        @csrf
                                        <button class="btn btn-danger btn-sm active">Remove</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

        <div class="justify-content-md-center p-5">
            <div class="col-md-auto">
                {{ $comments->links() }}
            </div>
        </div>

    </div>

@endsection