routes/web.php
<?php

use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\RatingsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::match(['get', 'post'], '/', [NewsController::class, 'index'])->name('home');
Route::resource('news', NewsController::class)->only('index','create', 'store','show');
Route::post('ratings', [RatingsController::class, 'store'])->name('store-rating')->middleware( 'auth');
Route::post('comments', [CommentsController::class, 'store'])->name('comments-store')->middleware( 'auth');
Route::get('users/{user}', [UsersController::class, 'show'])->name('show-user');


Route::prefix('admin')->middleware( 'auth')->name('admin.')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('admin-profile');
    Route::resource('news' ,App\Http\Controllers\Admin\NewsController::class)->except('show');
    Route::resource('comments' ,App\Http\Controllers\Admin\CommentController::class)->except('create','store','show');
    Route::post('comments-approve/{comment}', [CommentController::class, 'approve'])->name('comments-approve');
});

Auth::routes();

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class News extends Model
{
    use HasFactory;

    protected $fillable = ['text', 'tag_id', 'category_id', 'user_id', 'publication_date'];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo
     */
    public function tag(): BelongsTo
    {
        return $this->belongsTo(Tag::class);
    }


    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function ratings(): HasMany
    {
        return $this->hasMany(Rating::class);
    }


}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\NewsRequest;
use App\Models\Category;
use App\Models\News;
use App\Models\Tag;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class NewsController extends Controller
{

    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws AuthorizationException
     */
    public function index()
    {
        $this->authorize('index', News::class);
        $news = News::latest()->paginate(10);
        return view('admin.news.index', compact('news'));
    }


    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', News::class);
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.news.create', compact('categories', 'tags'));
    }


    /**
     * @param NewsRequest $request
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function store(NewsRequest $request)
    {
        $this->authorize('store', News::class);
        $news = new News();
        $news->text = $request->input('text');
        $news->category_id = $request->input('category_id');
        $news->tag_id = $request->input('tag_id');
        $news->user_id = auth()->user()->id;
        if($request->publication_date) {
            $news->publication_date = $request->input('publication_date');
        }
        $news->save();

        return redirect()->route('admin.news.index')
            ->with('status', "News created successfully!!!");
    }


    /**
     * @param News $news
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws AuthorizationException
     */
    public function edit(News $news)
    {
        $this->authorize('edit', News::class);
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.news.edit', compact('news', 'categories', 'tags'));
    }


    /**
     * @param NewsRequest $request
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(NewsRequest $request, News $news)
    {
        $this->authorize('update', News::class);
        $data = $request->all();
        $news->update($data);

        return redirect()->route('admin.news.index')
            ->with('status', "News update successfully!!!");
    }


    /**
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(News $news)
    {
        $this->authorize('destroy', News::class);
        $news->delete();
        return redirect()->action([self::class, 'index'])->with('status', "News successfully deleted!");
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NewsRequest;
use App\Models\Category;
use App\Models\News;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NewsController extends Controller
{

    /**
     * @param Request $request
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index(Request $request)
    {

        $now = Carbon::now();
        $categories = Category::all();
        $tags = Tag::all();
        $newsQuery = News::whereDate('publication_date', '<=', $now)->latest();

        if ($request->isMethod('post')) {
            if ($request->category == "Filter by category") {
                $tag_id = $request->tag;
                $newsQuery->where('tag_id', $tag_id);
            } else {
                $category_id = $request->category;
                $newsQuery->where('category_id', $category_id);
            }
        }

        $news = $newsQuery->paginate(8);

        return view('news.index', compact('news', 'categories', 'tags'));

    }

    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application|RedirectResponse
     */
    public function create()
    {
        if(Auth::check()) {
            $categories = Category::all();
            $tags = Tag::all();

            return view('news.create', compact('categories', 'tags'));
        }
        return redirect()->route('login');
    }


    /**
     * @param NewsRequest $request
     * @return RedirectResponse
     */
    public function store(NewsRequest $request)
    {

        $news = new News();
        $news->text = $request->input('text');
        $news->category_id = $request->input('category_id');
        $news->tag_id = $request->input('tag_id');
        $news->user_id = auth()->user()->id;
        $news->save();

        return redirect()->route('news.index')
            ->with('status', "News created successfully!!!");

    }


    /**
     * @param News $news
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function show(News $news)
    {
        return view('news.show', compact('news'));
    }

}

resources/views/admin/news/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mt-5">
        <div style="width: 80%; margin: 0 auto">
            <h2 class="mt-5">Create new news</h2>
            <form method="post" action="{{ route('admin.news.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="mb-3 mt-5" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <textarea type="text" name="text" class="form-control" placeholder="News text"
                              aria-label="news_text"
                              aria-describedby="addon-wrapping"></textarea>
                </div>
                @error('text')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div class="mb-3" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <select name="category_id" class="form-select" aria-label="Default select example">
                        <option value=" " selected>Choose category</option>
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                @error('category_id')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div class="mb-3" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <select name="tag_id" class="form-select" aria-label="Default select example">
                        <option value=" " selected>Choose tag</option>
                        @foreach($tags as $tag)
                            <option value="{{ $tag->id }}">{{ $tag->tag }}</option>
                        @endforeach
                    </select>
                </div>
                @error('tag_id')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div class="mb-3" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <input name="publication_date" class="form-select" aria-label="Default select example" type="date">
                </div>

                <div style="width: 15%;margin: 0 auto;">
                    <button type="submit" style="padding: 8px 50px; color: black" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/news/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mt-5">
        <div style="width: 80%; margin: 0 auto">
            <h2 class="mt-5">Update news</h2>
            <form method="post" action="{{ route('admin.news.update', ['news' => $news]) }}"
                  enctype="multipart/form-data">
                @method('put')
                @csrf
                <div class="mb-3 mt-5" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <textarea type="text" name="text" class="form-control" placeholder="News text"
                              aria-label="news_text"
                              aria-describedby="addon-wrapping">{{ $news->text }}</textarea>
                </div>
                @error('text')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div class="mb-3" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <select name="category_id" class="form-select" aria-label="Default select example">
                        @if(is_null($news->category_id))
                            <option value="{{ $news->category_id }}" selected>{{ $news->category->name }}</option>
                        @endif
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                @error('category_id')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div class="mb-3" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <select name="tag_id" class="form-select" aria-label="Default select example">
                        @if(is_null($news->tag_id))
                            <option value="{{ $news->tag_id }}" selected>{{ $news->tag->tag }}</option>
                        @endif
                        @foreach($tags as $tag)
                            <option value="{{ $tag->id }}">{{ $tag->tag }}</option>
                        @endforeach
                    </select>
                </div>
                @error('tag_id')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div class="mb-3" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <input name="publication_date" class="form-select" aria-label="Default select example" type="date">
                </div>

                <div style="width: 15%;margin: 0 auto;">
                    <button type="submit" style="padding: 8px 50px; color: black" class="btn btn-primary">Update
                    </button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/news/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mt-5">
        <div>
            <a href="{{ route('admin.news.create') }}" class="btn btn-primary" style="padding: 8px 30px;color: black">Create
                new news</a>
        </div>
        <div class="mt-3">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Text</th>
                    <th scope="col">Publication date</th>
                    <th scope="col">Created date</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($news as $item)
                    <tr>
                        <th scope="row">{{ $item->id }}</th>
                        <td>{{ $item->text }}</td>
                        @if($item->publication_date)
                            <td>{{ date_format(new DateTime($item->publication_date), 'd-m-y')  }}</td>
                        @else
                            <td></td>
                        @endif
                        <td>{{ date_format(new DateTime($item->created_at), 'd-m-y')  }}</td>
                        <td>

                            <div class="row">
                                <div class="col-6 box-btn">
                                    <a class="btn btn-outline-warning"
                                       href="{{ route('admin.news.edit', ['news' => $item]) }}">Edit
                                    </a>
                                    <form style="float: left; margin-right: 12px;"
                                          action="{{ route('admin.news.destroy', ['news' => $item]) }}" method="post">
                                        @method('delete')
                                        @csrf
                                        <button class="btn btn-danger btn-sm active">Remove</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

        <div class="justify-content-md-center p-5">
            <div class="col-md-auto">
                {{ $news->links() }}
            </div>
        </div>

    </div>

@endsection