routes/web.php
<?php

use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\RatingsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::match(['get', 'post'], '/', [NewsController::class, 'index'])->name('home');
Route::resource('news', NewsController::class)->only('index','create', 'store','show');
Route::post('ratings', [RatingsController::class, 'store'])->name('store-rating')->middleware( 'auth');
Route::post('comments', [CommentsController::class, 'store'])->name('comments-store')->middleware( 'auth');
Route::get('users/{user}', [UsersController::class, 'show'])->name('show-user');


Route::prefix('admin')->middleware( 'auth')->name('admin.')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('admin-profile');
    Route::resource('news' ,App\Http\Controllers\Admin\NewsController::class)->except('show');
    Route::resource('comments' ,App\Http\Controllers\Admin\CommentController::class)->except('create','store','show');
    Route::post('comments-approve/{comment}', [CommentController::class, 'approve'])->name('comments-approve');
});

Auth::routes();

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class News extends Model
{
    use HasFactory;

    protected $fillable = ['text', 'tag_id', 'category_id', 'user_id', 'publication_date'];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo
     */
    public function tag(): BelongsTo
    {
        return $this->belongsTo(Tag::class);
    }


    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function ratings(): HasMany
    {
        return $this->hasMany(Rating::class);
    }


}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\NewsRequest;
use App\Models\Category;
use App\Models\News;
use App\Models\Tag;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class NewsController extends Controller
{

    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws AuthorizationException
     */
    public function index()
    {
        $this->authorize('index', News::class);
        $news = News::latest()->paginate(10);
        return view('admin.news.index', compact('news'));
    }


    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', News::class);
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.news.create', compact('categories', 'tags'));
    }


    /**
     * @param NewsRequest $request
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function store(NewsRequest $request)
    {
        $this->authorize('store', News::class);
        $news = new News();
        $news->text = $request->input('text');
        $news->category_id = $request->input('category_id');
        $news->tag_id = $request->input('tag_id');
        $news->user_id = auth()->user()->id;
        if($request->publication_date) {
            $news->publication_date = $request->input('publication_date');
        }
        $news->save();

        return redirect()->route('admin.news.index')
            ->with('status', "News created successfully!!!");
    }


    /**
     * @param News $news
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws AuthorizationException
     */
    public function edit(News $news)
    {
        $this->authorize('edit', News::class);
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.news.edit', compact('news', 'categories', 'tags'));
    }


    /**
     * @param NewsRequest $request
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(NewsRequest $request, News $news)
    {
        $this->authorize('update', News::class);
        $data = $request->all();
        $news->update($data);

        return redirect()->route('admin.news.index')
            ->with('status', "News update successfully!!!");
    }


    /**
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(News $news)
    {
        $this->authorize('destroy', News::class);
        $news->delete();
        return redirect()->action([self::class, 'index'])->with('status', "News successfully deleted!");
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NewsRequest;
use App\Models\Category;
use App\Models\News;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NewsController extends Controller
{

    /**
     * @param Request $request
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index(Request $request)
    {

        $now = Carbon::now();
        $categories = Category::all();
        $tags = Tag::all();
        $newsQuery = News::whereDate('publication_date', '<=', $now)->latest();

        if ($request->isMethod('post')) {
            if ($request->category == "Filter by category") {
                $tag_id = $request->tag;
                $newsQuery->where('tag_id', $tag_id);
            } else {
                $category_id = $request->category;
                $newsQuery->where('category_id', $category_id);
            }
        }

        $news = $newsQuery->paginate(8);

        return view('news.index', compact('news', 'categories', 'tags'));

    }

    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application|RedirectResponse
     */
    public function create()
    {
        if(Auth::check()) {
            $categories = Category::all();
            $tags = Tag::all();

            return view('news.create', compact('categories', 'tags'));
        }
        return redirect()->route('login');
    }


    /**
     * @param NewsRequest $request
     * @return RedirectResponse
     */
    public function store(NewsRequest $request)
    {

        $news = new News();
        $news->text = $request->input('text');
        $news->category_id = $request->input('category_id');
        $news->tag_id = $request->input('tag_id');
        $news->user_id = auth()->user()->id;
        $news->save();

        return redirect()->route('news.index')
            ->with('status', "News created successfully!!!");

    }


    /**
     * @param News $news
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function show(News $news)
    {
        return view('news.show', compact('news'));
    }

}

resources/views/news/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mt-5">
        <div style="width: 80%; margin: 0 auto">
            <h2 class="mt-5">Create new news</h2>
            <form method="post" action="{{ route('news.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="mb-3 mt-5" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <textarea type="text" name="text" class="form-control" placeholder="News text"
                              aria-label="news_text"
                              aria-describedby="addon-wrapping"></textarea>
                </div>
                @error('text')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div class="mb-3" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <select name="category_id" class="form-select" aria-label="Default select example">
                        <option value=" " selected>Choose category</option>
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                @error('category_id')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div class="mb-3" style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                    <select name="tag_id" class="form-select" aria-label="Default select example">
                        <option value=" " selected>Choose tag</option>
                        @foreach($tags as $tag)
                            <option value="{{ $tag->id }}">{{ $tag->tag }}</option>
                        @endforeach
                    </select>
                </div>
                @error('tag_id')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror

                <div style="width: 15%;margin: 0 auto;">
                    <button type="submit" style="padding: 8px 50px; color: black" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/news/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="container mt-5">
        <form method="post" action="{{ route('home') }}">
            @csrf
            <div class="row mb-5">
                <div class="col-5">
                    <select class="form-select" name="category" aria-label="Default select example">
                        <option selected>Filter by category</option>
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-5">
                    <select class="form-select" name="tag" aria-label="Default select example">
                        <option selected>Filter by tag</option>
                        @foreach($tags as $tag)
                            <option value="{{ $tag->id }}">{{ $tag->tag }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-2">
                    <button type="submit" style="padding: 8px 50px; color: black" class="btn btn-primary">Search
                    </button>
                </div>
            </div>
        </form>

        <div class="row">
            @foreach($news as $item)
                <div class="col-3 mb-2">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <p class="card-text"><a
                                    href="{{ route('news.show', ['news' => $item]) }}">{{ $item->text }}</a></p>
                            <span>#{{ $item->tag->tag }}</span>
                            <p style="text-align: start"><a
                                    href="{{route('show-user', ['user' => $item->user])}}"><span>By: </span>{{$item->user->name}}
                                </a></p>
                            <p style="text-align: end">Publication
                                date: {{ date_format(new DateTime($item->publication_date), 'd-m-y') }} y.</p>
                            <p style="text-align: end">Created
                                date: {{ date_format(new DateTime($item->created_at), 'd-m-y') }} y.</p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

        <div class="justify-content-md-center p-5">
            <div class="col-md-auto">
                {{ $news->links() }}
            </div>
        </div>
    </div>


@endsection

resources/views/news/show.blade.php
@extends('layouts.app')
@section('content')

    <div class="container mt-5">
        <div class="d-flex">
            <div class="col-lg-6">
                <div style="padding-top: 70px; height: 65vh">
                    <div>
                        <h2 style="text-align: center">News</h2>
                        <p style="padding-top: 10px;">{{ $news->text }}</p>
                    </div>

                    @if(Auth::check())
                        <form method="post" action="{{ route('store-rating') }}">
                            @csrf
                            <input type="hidden" name="news_id" value="{{ $news->id }}">
                            <div>
                                <h3 style="text-align: center">Rate the news</h3>
                                <div class="row">
                                    <div class="col-4">
                                        <select name="quality" class="form-select" aria-label="Default select example">
                                            <option value=" " selected>Quality control</option>
                                            @for($i = -5; $i <= 5; $i++)
                                                <option value="{{ $i }}">{{ $i }}</option>
                                            @endfor
                                        </select>
                                        @error('quality')
                                        <div class="alert alert-danger">{{$message}}</div>
                                        @enderror
                                    </div>
                                    <div class="col-4">
                                        <select name="relevance" class="form-select"
                                                aria-label="Default select example">
                                            <option value=" " selected>Relevance control</option>
                                            @for($i = -5; $i <= 5; $i++)
                                                <option value="{{ $i }}">{{ $i }}</option>
                                            @endfor
                                        </select>
                                        @error('relevance')
                                        <div class="alert alert-danger">{{$message}}</div>
                                        @enderror
                                    </div>

                                    <div class="col-4">
                                        <input class="form-check-input" type="checkbox" value="0" name="satisfied"
                                               id="flexCheckDefault">
                                        <label class="form-check-label" for="flexCheckDefault">Satisfied</label>
                                    </div>
                                    <div class="mt-3" style="width: 15%;margin: 0 auto;">
                                        <button type="submit" style="padding: 8px 50px; color: black"
                                                class="btn btn-primary">Save
                                        </button>
                                    </div>
                                    @error('satisfied')
                                    <div class="alert alert-danger">{{$message}}</div>
                                    @enderror
                                </div>
                            </div>
                        </form>
                    @endif
                </div>
            </div>
            <div class="col-lg-6" style="text-align: center; padding: 0px 20px; ">
                <h1><b>Comments</b></h1>
                @if(Auth::check())
                    <form method="post" action="{{ route('comments-store') }}" id="create-comment">
                        <input type="hidden" name="news_id" value="{{ $news->id }}">
                        @csrf
                        <div style="display: flex; align-items: start; gap: 10px;justify-content: center;">
                            <lable for="text-comment">Text</lable>
                            <textarea name="comment" id="text-comment"
                                      style="border-radius: 5px; border: none;width: 350px;"></textarea>
                        </div>
                        @error('comments')
                        <div class="alert alert-danger mt-2"
                             style="display: flex; align-items: start; gap: 10px;justify-content: center;">{{$message}}</div>
                        @enderror

                        <div class="mt-3">
                            <button type="submit"
                                    style="padding: 7px 15px; border-radius: 10px; border: none;margin-bottom: 20px;">
                                add
                                comment
                            </button>
                        </div>
                    </form>
                @endif

                @foreach($news->comments as $comment)
                    @csrf
                    @if($comment->approve)
                        <div>
                            <div style="text-align: start;padding-left: 60px;">
                                <p class="m-0 p-0">By: <span>{{ $comment->user->name }} </span>
                                <p>{{ $comment->comment }}</p>
                            </div>
                            <hr>
                        </div>
                    @endif
                @endforeach
            </div>
        </div>
    </div>

@endsection